// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web-teller.proto

package wtproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type APIREQ struct {
	TxType               string            `protobuf:"bytes,1,opt,name=txType,proto3" json:"txType,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Params               map[string]string `protobuf:"bytes,3,rep,name=Params,proto3" json:"Params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *APIREQ) Reset()         { *m = APIREQ{} }
func (m *APIREQ) String() string { return proto.CompactTextString(m) }
func (*APIREQ) ProtoMessage()    {}
func (*APIREQ) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ef744ad4a9dc6f9, []int{0}
}

func (m *APIREQ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIREQ.Unmarshal(m, b)
}
func (m *APIREQ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIREQ.Marshal(b, m, deterministic)
}
func (m *APIREQ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIREQ.Merge(m, src)
}
func (m *APIREQ) XXX_Size() int {
	return xxx_messageInfo_APIREQ.Size(m)
}
func (m *APIREQ) XXX_DiscardUnknown() {
	xxx_messageInfo_APIREQ.DiscardUnknown(m)
}

var xxx_messageInfo_APIREQ proto.InternalMessageInfo

func (m *APIREQ) GetTxType() string {
	if m != nil {
		return m.TxType
	}
	return ""
}

func (m *APIREQ) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *APIREQ) GetParams() map[string]string {
	if m != nil {
		return m.Params
	}
	return nil
}

type APIRES struct {
	Response             []byte            `protobuf:"bytes,1,opt,name=Response,proto3" json:"Response,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=Headers,proto3" json:"Headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *APIRES) Reset()         { *m = APIRES{} }
func (m *APIRES) String() string { return proto.CompactTextString(m) }
func (*APIRES) ProtoMessage()    {}
func (*APIRES) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ef744ad4a9dc6f9, []int{1}
}

func (m *APIRES) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APIRES.Unmarshal(m, b)
}
func (m *APIRES) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APIRES.Marshal(b, m, deterministic)
}
func (m *APIRES) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APIRES.Merge(m, src)
}
func (m *APIRES) XXX_Size() int {
	return xxx_messageInfo_APIRES.Size(m)
}
func (m *APIRES) XXX_DiscardUnknown() {
	xxx_messageInfo_APIRES.DiscardUnknown(m)
}

var xxx_messageInfo_APIRES proto.InternalMessageInfo

func (m *APIRES) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *APIRES) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func init() {
	proto.RegisterType((*APIREQ)(nil), "wtproto.APIREQ")
	proto.RegisterMapType((map[string]string)(nil), "wtproto.APIREQ.HeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "wtproto.APIREQ.ParamsEntry")
	proto.RegisterType((*APIRES)(nil), "wtproto.APIRES")
	proto.RegisterMapType((map[string]string)(nil), "wtproto.APIRES.HeadersEntry")
}

func init() { proto.RegisterFile("web-teller.proto", fileDescriptor_0ef744ad4a9dc6f9) }

var fileDescriptor_0ef744ad4a9dc6f9 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0x49, 0xc2, 0x97, 0x7e, 0x9d, 0x96, 0xb6, 0x2c, 0x22, 0x21, 0x7a, 0x28, 0x3d, 0xf5,
	0x62, 0x0e, 0x09, 0x88, 0xf6, 0xd6, 0x43, 0xc1, 0xde, 0x62, 0x52, 0xf4, 0xbc, 0xb1, 0x83, 0x2e,
	0xa6, 0xbb, 0x71, 0x77, 0x63, 0xcd, 0xdd, 0x87, 0xf0, 0xe1, 0x7c, 0x18, 0x31, 0x59, 0xa5, 0x04,
	0xa1, 0x16, 0x6f, 0xf3, 0x9f, 0x99, 0xdf, 0x90, 0xfc, 0x16, 0x46, 0x5b, 0xcc, 0xce, 0x34, 0xe6,
	0x39, 0xca, 0xa0, 0x90, 0x42, 0x0b, 0xd2, 0xd9, 0xea, 0xba, 0x98, 0xbc, 0xda, 0xe0, 0xce, 0xe3,
	0x65, 0xb2, 0xb8, 0x26, 0xc7, 0xe0, 0xea, 0x97, 0x55, 0x55, 0xa0, 0x67, 0x8d, 0xad, 0x69, 0x37,
	0x31, 0x89, 0x9c, 0x43, 0xe7, 0x0a, 0xe9, 0x1a, 0xa5, 0xf2, 0xec, 0xb1, 0x33, 0xed, 0x85, 0xa7,
	0x81, 0xa1, 0x83, 0x86, 0x0c, 0xcc, 0x78, 0xc1, 0xb5, 0xac, 0x92, 0xaf, 0x65, 0x12, 0x81, 0x1b,
	0x53, 0x49, 0x37, 0xca, 0x73, 0x6a, 0xec, 0xa4, 0x8d, 0x35, 0xd3, 0x86, 0x32, 0xab, 0xfe, 0x0c,
	0xfa, 0xbb, 0xd7, 0xc8, 0x08, 0x9c, 0x47, 0xac, 0xcc, 0x17, 0x7d, 0x96, 0xe4, 0x08, 0xfe, 0x3d,
	0xd3, 0xbc, 0x44, 0xcf, 0xae, 0x7b, 0x4d, 0x98, 0xd9, 0x17, 0x96, 0x7f, 0x09, 0xbd, 0x9d, 0x93,
	0x87, 0xa0, 0x93, 0x37, 0xcb, 0x68, 0x48, 0x89, 0x0f, 0xff, 0x13, 0x54, 0x85, 0xe0, 0xaa, 0x11,
	0xd1, 0x4f, 0xbe, 0xf3, 0x5e, 0x15, 0xe9, 0xcf, 0x2a, 0xfe, 0xf2, 0x57, 0xe1, 0xbb, 0x05, 0xdd,
	0x5b, 0xcc, 0x56, 0xf5, 0xf3, 0x91, 0x10, 0x06, 0xf3, 0x52, 0x3f, 0x20, 0xd7, 0xec, 0x8e, 0x6a,
	0x26, 0x38, 0x19, 0xb6, 0xb4, 0xfa, 0xad, 0x46, 0x4a, 0x22, 0x18, 0xa6, 0xa8, 0x14, 0x13, 0xfc,
	0x86, 0xe6, 0x6c, 0x4d, 0x35, 0xfe, 0x02, 0x0a, 0x61, 0x10, 0xd3, 0x6a, 0x83, 0x5c, 0x2f, 0xf9,
	0x53, 0xc9, 0x64, 0x75, 0x10, 0x13, 0x0b, 0xa5, 0x19, 0xbf, 0xdf, 0xcf, 0x64, 0x6e, 0x9d, 0xa2,
	0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfc, 0xc0, 0x87, 0xcc, 0xa4, 0x02, 0x00, 0x00,
}
